# -*- coding: utf-8 -*-
"""Baseline_Finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLKsU6kmxA6X-Ll4-My5V2N2sDwP6LoR
"""

!pip install -q \
transformers==4.41.2 \
datasets==2.19.0 \
accelerate==0.30.1 \
peft==0.11.1 \
evaluate==0.4.2

import transformers
import datasets
import peft
import evaluate

print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("PEFT:", peft.__version__)

!pip install evaluate

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import numpy as np
from datasets import load_dataset
import time

dataset = load_dataset("imdb")
print(dataset)

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, num_labels=2
)
print("Model loaded successfully")

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )
tokenized_dataset = dataset.map(tokenize_function, batched=True)
tokenized_dataset = tokenized_dataset.remove_columns(["text"])
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")
tokenized_dataset.set_format("torch")

train_dataset = tokenized_dataset["train"].shuffle(seed=42).select(range(2000))
eval_dataset = tokenized_dataset["test"].shuffle(seed=42).select(range(500))

metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
)

!pip install numpy==1.26.4

start_time = time.time()
trainer.train()
end_time = time.time()
print("Training Time (seconds):", end_time - start_time)

results = trainer.evaluate()
print(results)