# -*- coding: utf-8 -*-
"""LoRA_Fine_Tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUkbinOrgUbC_NBJwdoO-MG-jqPrk1dE
"""

!pip install peft==0.11.1 -q

!pip install evaluate==0.4.2

import torch
import time
import numpy as np
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from peft import get_peft_model, LoraConfig, TaskType
import evaluate

dataset = load_dataset("imdb")

# ── Cell 4: Tokenizer — MATCHED to your baseline ─────────────────────────────
model_name = "distilbert-base-uncased"
tokenizer  = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",   # matched to your baseline
        max_length=128,          # matched to your baseline
    )

tokenized_dataset = dataset.map(tokenize_function, batched=True)
tokenized_dataset = tokenized_dataset.remove_columns(["text"])
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")
tokenized_dataset.set_format("torch")

# Same split as your baseline
train_dataset = tokenized_dataset["train"].shuffle(seed=42).select(range(2000))
eval_dataset  = tokenized_dataset["test"].shuffle(seed=42).select(range(500))

# ── Cell 5: Load Model + Apply LoRA ──────────────────────────────────────────
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_lin", "v_lin"],  # DistilBERT-specific names
    bias="none",
)

model = get_peft_model(model, lora_config)

# ── Cell 6: Count Trainable Parameters ───────────────────────────────────────
def count_parameters(model):
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total     = sum(p.numel() for p in model.parameters())
    print(f"{'Trainable params:':<25} {trainable:>12,}")
    print(f"{'Frozen params:':<25} {total - trainable:>12,}")
    print(f"{'Total params:':<25} {total:>12,}")
    print(f"{'Trainable %:':<25} {100 * trainable / total:>11.4f}%")
    return trainable, total

trainable_params, total_params = count_parameters(model)

# ── Cell 7: Metrics (same as your baseline) ──────────────────────────────────
from sklearn.metrics import accuracy_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {"accuracy": accuracy_score(labels, predictions)}

# ── Cell 8: Training Args — only LR changed vs your baseline ─────────────────
training_args = TrainingArguments(
    output_dir="./lora-results",
    eval_strategy="epoch",
    learning_rate=3e-4,              # higher LR is correct for LoRA
    per_device_train_batch_size=16,  # matched
    per_device_eval_batch_size=16,   # matched
    fp16=torch.cuda.is_available(),
    num_train_epochs=2,              # matched
    weight_decay=0.01,               # matched
    logging_dir="./logs",            # matched
    logging_steps=50,                # matched
    report_to="none",                # disables W&B prompt
)

# ── Cell 9: Trainer ───────────────────────────────────────────────────────────
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
)

# ── Cell 10: Train + Time ─────────────────────────────────────────────────────
start_time = time.time()
trainer.train()
lora_time = time.time() - start_time
print("Training Time (seconds):", lora_time)

# ── Cell 11: Evaluate ─────────────────────────────────────────────────────────
results = trainer.evaluate()
print(results)
lora_accuracy = results["eval_accuracy"]

# ── Cell 12: Final Comparison Table ───────────────────────────────────────────
BASELINE_PARAMS = 66_955_010  # full DistilBERT trainable params

print("\n" + "="*58)
print(f"{'Metric':<28} {'Full Fine-Tune':>14} {'LoRA':>12}")
print("="*58)
print(f"{'Accuracy':<28} {'0.822':>14} {lora_accuracy:>12.3f}")
print(f"{'Training Time (s)':<28} {'117.43':>14} {lora_time:>12.1f}")
print(f"{'Trainable Params':<28} {BASELINE_PARAMS:>14,} {trainable_params:>12,}")
print(f"{'% Params Trained':<28} {'100.00%':>14} {100*trainable_params/total_params:>11.4f}%")
print("="*58)